version: '3.3'
services:
  odoo:
    build: .
    image: image_odoo_14
    container_name: cont_odoo_14_p1
    depends_on:
      - db
    volumes:
      - "./data-odoo-14:/filestore"
      - "./src:/opt/odoo"
      - "./extra-addons:/opt/odoo/extra-addons"
      - "./data-log-14:/var/log/odoo/"
    environment:
      - ODOO_DB_USER=odoo
      - ODOO_DB_PASSWORD=odoo
      - ODOO_DB_HOST=db
      - ODOO_ADMIN_PASSWORD=randompass
    ports:
      - "8069:8069"
      - "8072:8069"
    restart: always
    command: "/opt/odoo/odoo-bin -c /opt/odoo/.odoorc"
    #command: "tail -f /dev/null"
    networks: 
      - red-odoo14
  db:
    image: postgres:9.6
    container_name: cont_db_14_p1
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_DB=postgres      
      - PG_SYSTEM_SHARED_BUFFERS=256MB
      - PG_SYSTEM_MAINTENANCE_WORK_MEM=256MB
      - PG_SYSTEM_WAL_BUFFERS=8MB
      - PG_SYSTEM_EFFECTIVE_CACHE_SIZE=1024MB
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - "./data-db-14:/var/lib/postgresql/data/pgdata"
    restart: always
    networks: 
      - red-odoo14
      
networks:
   red-odoo14:
  
volumes:
  data-odoo-14:
  data-db-14:
  data-log-14:
  extra-addons: